# Generated by Django 3.1.7 on 2021-11-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetailsModel',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('card_type_id', models.IntegerField()),
                ('card_number', models.IntegerField()),
                ('card_limit', models.IntegerField()),
                ('issued_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CardTypesModel',
            fields=[
                ('card_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('limit', models.IntegerField()),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LimitIncreaseRequestModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('card_id', models.IntegerField()),
                ('final_limit', models.IntegerField()),
                ('status', models.IntegerField()),
                ('remark', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('card_type_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('remark', models.CharField(max_length=40)),
            ],
        ),
    ]
