# Generated by Django 3.1.7 on 2021-11-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0002_auto_20211128_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtypesmodel',
            name='card_type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
