# Generated by Django 3.1.7 on 2021-11-30 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0003_auto_20211128_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carddetailsmodel',
            old_name='card_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='customermodel',
            old_name='id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='limitincreaserequestmodel',
            old_name='card_id',
            new_name='card_type_id',
        ),
    ]
