# Generated by Django 4.0 on 2022-07-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0004_auto_20211201_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetailsmodel',
            name='expiration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='carddetailsmodel',
            name='issued_date',
            field=models.DateField(),
        ),
    ]
