# Generated by Django 4.0 on 2022-07-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0006_alter_carddetailsmodel_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetailsmodel',
            name='expiration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='carddetailsmodel',
            name='issued_date',
            field=models.DateField(),
        ),
    ]
